controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_compte_edit:
  path: /compte/edit
  controller: App\Controller\AccountController::edit